Gw 22 develop about section
gisauweb/GISAUBC pull request #11
Opened 2023-01-12 02:02 UTC by chrishadrian

2023-01-12 02:25 UTC, Julian-UBC commented
@chrishadrian @jenaarianto Here is the website preview: https://deploy-preview-11--gisaubcv3.netlify.app/

2023-01-12 02:32 UTC, jenaarianto approved these changes

2023-01-16 04:57 UTC, jenaarianto reviewed
I think it'd be easier on they eyes if the 'who we are' section has a slightly smaller font and di kebawahin more

2023-01-17 05:14 UTC, Julian-UBC requested changes

2023-01-17 05:24 UTC, Julian-UBC commented on public/index.html
> +    <link rel="apple-touch-icon" href="%PUBLIC_URL%/gisau_icon.svg" />
Test comment

2023-01-17 06:31 UTC, chrishadrian commented on src/pages/home/components/About.js
> +        <Box className={`flex w-2/5 ${classes.bgImage}`}>
Fixed

2023-01-17 06:32 UTC, chrishadrian commented on src/pages/home/components/LandingImage.js
> +import LandingImg from "../../../assets/landing.jpg";
To get better naming and folder structure. What do you think?

2023-01-17 06:33 UTC, chrishadrian commented on src/pages/home/components/About.js
> +      transitionTimingFunction: "ease-out",
Modified a few properties on the button's styles.

2023-01-17 23:05 UTC, Julian-UBC commented on src/pages/home/components/LandingImage.js
> +import LandingImg from "../../../assets/landing.jpg";
I had the idea that we will have more than one image for the landing image and not necessarily want to delete the previous one. That's why I put them under a folder.

2023-01-17 23:45 UTC, Julian-UBC reviewed
Will just leave two comments here:
1. Somehow the `i` doesn't look good here, the dot seems like merging with the body 
![image](https://user-images.githubusercontent.com/84741001/213032677-d1deff60-c0bb-4a0b-b630-3af4b1486cd1.png)

2. The button transition still doesn't look smooth enough like the design made by @jenaarianto . This doesn't have to be resolved now. Will just update it in the GW-28.

2023-01-17 23:46 UTC, Julian-UBC approved these changes

2023-01-18 06:51 UTC, merged