Gw 92: Added sponsorship partner contact info
gisauweb/GISAUBC pull request #139
Opened 2023-10-27 07:48 UTC by msamanthaf

Does this align with what you had in mind? Any suggestions/anything to add?

![image](https://github.com/gisauweb/GISAUBC/assets/104884933/b525bde4-a3bc-444d-9d66-0ac7c87a3379)

2023-10-27 08:24 UTC, chrishadrian reviewed
Looks good so far! I don’t know about the button tho? Should we ask our designers to design it for us? I’d also want to redesign how to access our sponsors not gonna lie.

2023-10-27 08:24 UTC, chrishadrian commented on client/src/pages/partners/components/PartnerContact.jsx
> +						<a href='mailto:contact.gisau@gmail.com'>Contact us at sponsorship.gisau@gmail.com</a>
a should be wrapping Box imi

2023-11-01 03:32 UTC, chrishadrian requested changes
Can you remove halloween page from the website too?

2023-11-02 06:39 UTC, msamanthaf commented
Dy think it's better to keep the font the way it was before or the reduced/smaller version?

2023-11-04 03:10 UTC, chrishadrian commented
Font looks good but spacing still needs to change:
<img width="348" alt="image" src="https://github.com/gisauweb/GISAUBC/assets/65900990/c7adea6e-3697-4adc-a26e-8c41f05647fa">. I'd say make it to have an even space

2023-11-04 03:10 UTC, chrishadrian commented
And don't forget to remove halloween event from current event 👍

2023-11-04 19:41 UTC, chrishadrian approved these changes
LOOKS GOODDD!!

2023-11-04 19:42 UTC, merged