GW-25: Develop partners section in home page
gisauweb/GISAUBC pull request #14
Opened 2023-01-30 07:36 UTC by chrishadrian

2023-01-30 09:18 UTC, jenaarianto approved these changes

2023-02-02 05:54 UTC, Julian-UBC requested changes
Next time don't forget to put `feature/` in front of your branch name

2023-02-02 05:54 UTC, Julian-UBC commented on src/pages/home/components/Activities/Activities.js
> +import { activities, smiley } from "../Activities/constants";
Why did you capitalize the folder name? Any reason?

2023-02-02 08:18 UTC, Julian-UBC requested changes
Include descriptions of what you have implemented and/or changed in this PR

2023-02-07 02:28 UTC, chrishadrian commented
Last commit should be a merge commit. Ignore the commit message.

2023-02-07 04:23 UTC, Julian-UBC approved these changes

2023-02-07 06:09 UTC, merged