Feature/gw 40 develop activities section to be responsive
gisauweb/GISAUBC pull request #18
Opened 2023-02-14 04:22 UTC by chrishadrian

2023-02-28 17:38 UTC, Julian-UBC requested changes
- [x] Can you rebase the branch with develop first?

2023-03-02 01:47 UTC, jenaarianto approved these changes

2023-03-02 02:07 UTC, Julian-UBC requested changes

2023-03-02 02:07 UTC, Julian-UBC commented on src/pages/home/components/About.js
> +const typographyStyle = "text-base sm:text-base xl:text-xl font-proxima-nova my-5 w-full sm:pr-6";
```suggestion
const typographyStyle = "text-base xl:text-xl font-proxima-nova my-5 w-full sm:pr-6";
```

2023-03-02 02:16 UTC, Julian-UBC reviewed
Good job @chrishadrian!! It looks good

2023-03-02 02:16 UTC, Julian-UBC reviewed
Resolved

2023-03-02 02:17 UTC, Julian-UBC approved these changes
Approved

2023-03-02 03:22 UTC, merged