GW-44: upcoming page placeholder
gisauweb/GISAUBC pull request #23
Opened 2023-03-05 22:58 UTC by Julian-UBC

- Created a layout for upcoming page (which is still in production)
- Refactor navigation bar so it works for all pages

Deploy preview:

2023-03-07 06:47 UTC, chrishadrian requested changes
LGTM. Bug found: URL not found when user hit refresh on the browser

2023-03-07 07:30 UTC, jenaarianto approved these changes

2023-03-09 03:12 UTC, Julian-UBC commented
> LGTM. Bug found: URL not found when user hit refresh on the browser

Good catch @chrishadrian! Fixed.

2023-03-09 08:08 UTC, chrishadrian approved these changes

2023-03-09 08:09 UTC, merged