GW-56: Develop upcoming events in events page
gisauweb/GISAUBC pull request #50
Opened 2023-05-04 10:12 UTC by Julian-UBC

- Created a short landing message in events page
- Modify the events layout to accommodate events page's design 

Example when there are multiple upcoming events: 
![Screenshot 2023-05-04 at 02-46-45 GISAUBC – Gado-Gado Indonesian Students Association of UBC](https://user-images.githubusercontent.com/84741001/236175748-49c96e7f-a90b-4edd-beb2-c6d81099ad4c.png)

2023-05-04 22:36 UTC, chrishadrian requested changes

2023-05-04 22:36 UTC, chrishadrian commented on src/shared/layout/MainContainer.js
> +  return <div className={`${className} w-4/5 mx-auto`}>{children}</div>;
Can you replace the className with the literal value of `mt-20` here? Container like this shouldn't have dynamic styles. Also adjust the other pages once you put mt-20 here.

2023-05-04 22:36 UTC, chrishadrian commented on src/shared/layout/event-layout/EventLayout.js
> +    content = (
Not to be rude but can you revert this? I already got a cleaner responsive grid layout for this. Or you can just leave it and I will adjust it in my PR.

2023-05-04 22:36 UTC, chrishadrian commented on src/shared/layout/event-layout/EventLayout.js
> +      <div className={`${isEventsPage ? `mt-16` : `mt-10`}`}>{content}</div>
This too

2023-05-04 22:36 UTC, chrishadrian commented on src/pages/events/Events.js
> +          <EventLayout
This too

2023-05-18 19:54 UTC, gisauweb approved these changes

2023-05-19 00:01 UTC, chrishadrian commented
This PR is included in another PR (https://github.com/gisauweb/GISAUBC/pull/51).

2023-05-19 00:01 UTC, closed without merging